[package]
name = "hash-tool"
version = "0.1.0"
authors = ["meowtec"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.99"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }
sha2 = "0.10.9"
digest = "0.10.7"
md-5 = "0.10.6"
sha1 = "0.10.6"
hex = "0.4.3"
crc = "3.3.0"
sm3 = "0.4.2"
sha3 = "0.10.8"

[dev-dependencies]
wasm-bindgen-test = "0.3.49"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
